exp_name: RAF-Furnished-16K-0.1%
pathspace:
  n_base_directions: 2048
  res: 128
start_bounce: 4
max_bounce: 4
start_growing_epoch: 300
growing_interval: 100
save_interval: 100
eval_interval: 50
vis_interval: 50
decay_loss: true
decay_loss_lambda: 1.0
pink_noise_supervision: false
pink_start_epoch: 500
lambda_pink: 0.2
n_epochs: 1000
no_terminal: false
hrirs_cache_dir: .working/hrir/
optimizer: Adam
renderer: refl_model
learning_rate:
  base: 0.0005
  spec: 0.0001
  diffuse: 5.0e-05
  source: 0.0005
  source_ir: 0.005
  late: 5.0e-05
  diffuse_basis: 0.0005
  feature_extractor: 0.0001
batch_size: 1
shuffle: true
sampler_opts:
  name: beam_tracing
  options:
    num_sample_directions: 16384
    dist_thresh: 5.0
loss_opts:
  name: diffrir_loss
  options:
    nffts:
    - 128
    - 512
    - 1024
    - 2048
    cutoff: 3000
    eps: 1.0e-06
clip_value: 0.1
enable_reg_ambient:
  lambda: 1.0
  multiplier: const
lr_scheduler:
  name: StepLR
  options:
    step_size: 1500
    gamma: 0.97
visualization:
  wave_visualization: false
  directivity_visualization: true
  path_visualization: true
model:
  frequency_min: 100
  frequency_max: 7500
  frequency_num: 32
  filter_length: 127
  feat_extractor_opts:
    name: mv_xformer_attn_only_feat_extractor
    options:
      out_channels: 512
      voxels_path: ${raf_feature_dir}/FurnishedRoom/voxels.npy
      voxel_features_path: ${raf_feature_dir}/FurnishedRoom/features.npy
      voxel_feature_scores_path: ${raf_feature_dir}/FurnishedRoom/scores.npy
      voxel_feature_camera_ids_path: ${raf_feature_dir}/FurnishedRoom/cam_ids.npy
      extrinsics_path: ${raf_feature_dir}/FurnishedRoom/extrinsics.npy
      voxel_size: 0.2
      num_heads: 8
      dim_key: 128
      dim_value: 128
      pe_order: 20
      num_hidden_layers: 1
      k_neighbors: 5
      use_res_connection: false
      dim_kqv_point: 128
      k_neighbors_query: 7
  src_opts:
    name: src_para_windowed
    options:
      filter_length: 127
      forced_offset: 40
      window_size: 80
  src_ir_opts:
    name: parameterized_directional_source
    options:
      sharpness: 8
      out_dim: 32
      n_base_directions: 128
  spec_ir_opts:
    name: specular_pe_mlp
    options:
      dim_feat: 512
      dim_out: 32
      n_layers: 4
      hidden_size: 256
      use_residual: false
      fuse_pe: true
      fuse_vision: true
      pe_order: 20
      xyz_scale:
      - 20
      - 5
      - 20
      activation: exp_softplus
  late_ir_opts:
    name: residual_para_direct
    options:
      rir_length: 5120
  diffuse_ir_opts:
    name: positional_encoding_acoustic_field
    options:
      xyz_min: -6.0
      xyz_max: 6.0
      xyz_order: 18
      dir_order: 10
      quat_order: 10
      output_dim: 5120
      n_layers: 4
      n_features: 256
      normalized: true