defaults:
  - _self_

name: diff_rir
scene_name: dampenedBase
path: ${haa_data_dir}/dampenedBase
rir_length: 32000
sample_rate: 16000
split_file: data-split/hearing_anything_anywhere/dampenedBase_split.json
options:
  n_points: 100000
  dim_feat: 8
  sample_rate: 16000
  speed_of_sound: 340.0
  source_xyz: [2.4542, 2.4981, 1.2654]
  mesh_path:  ${mesh_dir}/dampenedBase.obj